//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// AnalyticsDimPersonHistorical GraphQL Type
    /// </summary>
    public partial class AnalyticsDimPersonHistorical : ModelGraphType<Rock.Model.AnalyticsDimPersonHistorical>
    {
       public AnalyticsDimPersonHistorical(): base("AnalyticsDimPersonHistorical")
       {
          Field("Age", x => x.Age, nullable: true);
          Field("AnniversaryDate", x => x.AnniversaryDate, nullable: true);
          //Field<Rock.GraphQL.Types.AnalyticsDimDate>("BirthDateDim", resolve: x => x.Source.BirthDateDim);
          Field("BirthDateKey", x => x.BirthDateKey, nullable: true);
          Field("BirthDay", x => x.BirthDay, nullable: true);
          Field("BirthMonth", x => x.BirthMonth, nullable: true);
          Field("BirthYear", x => x.BirthYear, nullable: true);
          Field("ConnectionStatus", x => x.ConnectionStatus, nullable: false);
          Field("ConnectionStatusValueId", x => x.ConnectionStatusValueId, nullable: true);
          Field("CurrentRowIndicator", x => x.CurrentRowIndicator, nullable: false);
          Field("EffectiveDate", x => x.EffectiveDate, nullable: false);
          Field("Email", x => x.Email, nullable: false);
          Field("EmailPreference", x => x.EmailPreference.ConvertToInt(), nullable: false);
          Field("EmailPreferenceText", x => x.EmailPreferenceText, nullable: false);
          Field("ExpireDate", x => x.ExpireDate, nullable: false);
          Field("FirstName", x => x.FirstName, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("Gender", x => x.Gender.ConvertToInt(), nullable: false);
          Field("GenderText", x => x.GenderText, nullable: false);
          Field("GivingGroupId", x => x.GivingGroupId, nullable: true);
          Field("GivingId", x => x.GivingId, nullable: false);
          Field("GivingLeaderId", x => x.GivingLeaderId, nullable: true);
          Field("GraduationYear", x => x.GraduationYear, nullable: true);
          Field("InactiveReasonNote", x => x.InactiveReasonNote, nullable: false);
          Field("IsDeceased", x => x.IsDeceased, nullable: false);
          Field("LastName", x => x.LastName, nullable: false);
          Field("MaritalStatus", x => x.MaritalStatus, nullable: false);
          Field("MaritalStatusValueId", x => x.MaritalStatusValueId, nullable: true);
          Field("MiddleName", x => x.MiddleName, nullable: false);
          Field("NickName", x => x.NickName, nullable: false);
          Field("PersonId", x => x.PersonId, nullable: false);
          Field("PhotoId", x => x.PhotoId, nullable: true);
          Field("PrimaryFamilyId", x => x.PrimaryFamilyId, nullable: true);
          Field("PrimaryFamilyKey", x => x.PrimaryFamilyKey, nullable: true);
          Field("RecordStatus", x => x.RecordStatus, nullable: false);
          Field("RecordStatusLastModifiedDateTime", x => x.RecordStatusLastModifiedDateTime, nullable: true);
          Field("RecordStatusReason", x => x.RecordStatusReason, nullable: false);
          Field("RecordStatusReasonValueId", x => x.RecordStatusReasonValueId, nullable: true);
          Field("RecordStatusValueId", x => x.RecordStatusValueId, nullable: true);
          Field("RecordType", x => x.RecordType, nullable: false);
          Field("RecordTypeValueId", x => x.RecordTypeValueId, nullable: true);
          Field("ReviewReason", x => x.ReviewReason, nullable: false);
          Field("ReviewReasonNote", x => x.ReviewReasonNote, nullable: false);
          Field("ReviewReasonValueId", x => x.ReviewReasonValueId, nullable: true);
          Field("Suffix", x => x.Suffix, nullable: false);
          Field("SuffixValueId", x => x.SuffixValueId, nullable: true);
          Field("SystemNote", x => x.SystemNote, nullable: false);
          Field("Title", x => x.Title, nullable: false);
          Field("TitleValueId", x => x.TitleValueId, nullable: true);
          Field("ViewedCount", x => x.ViewedCount, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.AnalyticsDimPersonHistorical GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.AnalyticsDimPersonHistoricalService(context.db);
           return service.Get(id);
       }
   }
}
