//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// AuditDetail GraphQL Type
    /// </summary>
    public partial class AuditDetail : ModelGraphType<Rock.Model.AuditDetail>
    {
       public AuditDetail(): base("AuditDetail")
       {
          Field("AuditId", x => x.AuditId, nullable: false);
          Field("CurrentValue", x => x.CurrentValue, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("OriginalValue", x => x.OriginalValue, nullable: false);
          Field("Property", x => x.Property, nullable: false);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.AuditDetail GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.AuditDetailService(context.db);
           return service.Get(id);
       }
   }
}
