//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// BinaryFileType GraphQL Type
    /// </summary>
    public partial class BinaryFileType : ModelGraphType<Rock.Model.BinaryFileType>
    {
       public BinaryFileType(): base("BinaryFileType")
       {
          Field("AllowCaching", x => x.AllowCaching, nullable: false);
          Field("Description", x => x.Description, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IconCssClass", x => x.IconCssClass, nullable: false);
          Field("IsSystem", x => x.IsSystem, nullable: false);
          Field("MaxHeight", x => x.MaxHeight, nullable: true);
          Field("MaxWidth", x => x.MaxWidth, nullable: true);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field("Name", x => x.Name, nullable: false);
          Field("PreferredColorDepth", x => x.PreferredColorDepth.ConvertToInt(), nullable: false);
          Field("PreferredFormat", x => x.PreferredFormat.ConvertToInt(), nullable: false);
          Field("PreferredRequired", x => x.PreferredRequired, nullable: false);
          Field("PreferredResolution", x => x.PreferredResolution.ConvertToInt(), nullable: false);
          Field("RequiresViewSecurity", x => x.RequiresViewSecurity, nullable: false);
          Field<Rock.GraphQL.Types.EntityType>("StorageEntityType", resolve: x => x.Source.StorageEntityType);
          Field("StorageEntityTypeId", x => x.StorageEntityTypeId, nullable: true);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.BinaryFileType GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.BinaryFileTypeService(context.db);
           return service.Get(id);
       }
   }
}
