//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// ConnectionRequest GraphQL Type
    /// </summary>
    public partial class ConnectionRequest : ModelGraphType<Rock.Model.ConnectionRequest>
    {
       public ConnectionRequest(): base("ConnectionRequest")
       {
          Field("AssignedGroupId", x => x.AssignedGroupId, nullable: true);
          Field("AssignedGroupMemberAttributeValues", x => x.AssignedGroupMemberAttributeValues, nullable: false);
          Field("AssignedGroupMemberRoleId", x => x.AssignedGroupMemberRoleId, nullable: true);
          Field("AssignedGroupMemberStatus", x => x.AssignedGroupMemberStatus.ConvertToInt(), nullable: true);
          Field("CampusId", x => x.CampusId, nullable: true);
          Field("Comments", x => x.Comments, nullable: false);
          Field<Rock.GraphQL.Types.ConnectionOpportunity>("ConnectionOpportunity", resolve: x => x.Source.ConnectionOpportunity);
          Field("ConnectionOpportunityId", x => x.ConnectionOpportunityId, nullable: false);
          Field<Rock.GraphQL.Types.ConnectionStatus>("ConnectionStatus", resolve: x => x.Source.ConnectionStatus);
          Field("ConnectionStatusId", x => x.ConnectionStatusId, nullable: false);
          Field("ConnectorPersonAliasId", x => x.ConnectorPersonAliasId, nullable: true);
          Field("FollowupDate", x => x.FollowupDate, nullable: true);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("PersonAlias", resolve: x => x.Source.PersonAlias);
          Field("PersonAliasId", x => x.PersonAliasId, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.ConnectionRequest GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.ConnectionRequestService(context.db);
           return service.Get(id);
       }
   }
}
