//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// ContentChannelItem GraphQL Type
    /// </summary>
    public partial class ContentChannelItem : ModelGraphType<Rock.Model.ContentChannelItem>
    {
       public ContentChannelItem(): base("ContentChannelItem")
       {
          Field("AllowsInteractiveBulkIndexing", x => x.AllowsInteractiveBulkIndexing, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ApprovedByPersonAlias", resolve: x => x.Source.ApprovedByPersonAlias);
          Field("ApprovedByPersonAliasId", x => x.ApprovedByPersonAliasId, nullable: true);
          Field("ApprovedDateTime", x => x.ApprovedDateTime, nullable: true);
          Field<ListGraphType<Rock.GraphQL.Types.ContentChannelItemAssociation>>("ChildItems", resolve: x => x.Source.ChildItems);
          Field("Content", x => x.Content, nullable: false);
          Field<Rock.GraphQL.Types.ContentChannel>("ContentChannel", resolve: x => x.Source.ContentChannel);
          Field("ContentChannelId", x => x.ContentChannelId, nullable: false);
          Field<Rock.GraphQL.Types.ContentChannelType>("ContentChannelType", resolve: x => x.Source.ContentChannelType);
          Field("ContentChannelTypeId", x => x.ContentChannelTypeId, nullable: false);
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field<ListGraphType<Rock.GraphQL.Types.EventItemOccurrenceChannelItem>>("EventItemOccurrences", resolve: x => x.Source.EventItemOccurrences);
          Field("ExpireDateTime", x => x.ExpireDateTime, nullable: true);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field("Order", x => x.Order, nullable: false);
          Field<ListGraphType<Rock.GraphQL.Types.ContentChannelItemAssociation>>("ParentItems", resolve: x => x.Source.ParentItems);
          Field("Permalink", x => x.Permalink, nullable: false);
          Field("Priority", x => x.Priority, nullable: false);
          Field("StartDateTime", x => x.StartDateTime, nullable: false);
          Field("Status", x => x.Status.ConvertToInt(), nullable: false);
          Field("Title", x => x.Title, nullable: false);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.ContentChannelItem GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.ContentChannelItemService(context.db);
           return service.Get(id);
       }
   }
}
