//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// EventItemOccurrence GraphQL Type
    /// </summary>
    public partial class EventItemOccurrence : ModelGraphType<Rock.Model.EventItemOccurrence>
    {
       public EventItemOccurrence(): base("EventItemOccurrence")
       {
          Field<Rock.GraphQL.Types.Campus>("Campus", resolve: x => x.Source.Campus);
          Field("CampusId", x => x.CampusId, nullable: true);
          Field("ContactEmail", x => x.ContactEmail, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ContactPersonAlias", resolve: x => x.Source.ContactPersonAlias);
          Field("ContactPersonAliasId", x => x.ContactPersonAliasId, nullable: true);
          Field("ContactPhone", x => x.ContactPhone, nullable: false);
          Field<ListGraphType<Rock.GraphQL.Types.EventItemOccurrenceChannelItem>>("ContentChannelItems", resolve: x => x.Source.ContentChannelItems);
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field<Rock.GraphQL.Types.EventItem>("EventItem", resolve: x => x.Source.EventItem);
          Field("EventItemId", x => x.EventItemId, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field<ListGraphType<Rock.GraphQL.Types.EventItemOccurrenceGroupMap>>("Linkages", resolve: x => x.Source.Linkages);
          Field("Location", x => x.Location, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field("NextStartDateTime", x => x.NextStartDateTime, nullable: true);
          Field("Note", x => x.Note, nullable: false);
          Field<Rock.GraphQL.Types.Schedule>("Schedule", resolve: x => x.Source.Schedule);
          Field("ScheduleId", x => x.ScheduleId, nullable: true);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.EventItemOccurrence GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.EventItemOccurrenceService(context.db);
           return service.Get(id);
       }
   }
}
