//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// EventItemAudience GraphQL Type
    /// </summary>
    public partial class EventItemAudience : ModelGraphType<Rock.Model.EventItemAudience>
    {
       public EventItemAudience(): base("EventItemAudience")
       {
          Field<Rock.GraphQL.Types.DefinedValue>("DefinedValue", resolve: x => x.Source.DefinedValue);
          Field("DefinedValueId", x => x.DefinedValueId, nullable: false);
          Field<Rock.GraphQL.Types.EventItem>("EventItem", resolve: x => x.Source.EventItem);
          Field("EventItemId", x => x.EventItemId, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.EventItemAudience GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.EventItemAudienceService(context.db);
           return service.Get(id);
       }
   }
}
