//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// ExceptionLog GraphQL Type
    /// </summary>
    public partial class ExceptionLog : ModelGraphType<Rock.Model.ExceptionLog>
    {
       public ExceptionLog(): base("ExceptionLog")
       {
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field("Cookies", x => x.Cookies, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("Description", x => x.Description, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field("ExceptionType", x => x.ExceptionType, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("Form", x => x.Form, nullable: false);
          Field("HasInnerException", x => x.HasInnerException, nullable: true);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field<Rock.GraphQL.Types.Page>("Page", resolve: x => x.Source.Page);
          Field("PageId", x => x.PageId, nullable: true);
          Field("PageUrl", x => x.PageUrl, nullable: false);
          Field("ParentId", x => x.ParentId, nullable: true);
          Field("QueryString", x => x.QueryString, nullable: false);
          Field("ServerVariables", x => x.ServerVariables, nullable: false);
          Field<Rock.GraphQL.Types.Site>("Site", resolve: x => x.Source.Site);
          Field("SiteId", x => x.SiteId, nullable: true);
          Field("Source", x => x.Source, nullable: false);
          Field("StackTrace", x => x.StackTrace, nullable: false);
          Field("StatusCode", x => x.StatusCode, nullable: false);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.ExceptionLog GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.ExceptionLogService(context.db);
           return service.Get(id);
       }
   }
}
