//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// FinancialScheduledTransaction GraphQL Type
    /// </summary>
    public partial class FinancialScheduledTransaction : ModelGraphType<Rock.Model.FinancialScheduledTransaction>
    {
       public FinancialScheduledTransaction(): base("FinancialScheduledTransaction")
       {
          Field("AuthorizedPersonAliasId", x => x.AuthorizedPersonAliasId, nullable: false);
          Field("CardReminderDate", x => x.CardReminderDate, nullable: true);
          Field("EndDate", x => x.EndDate, nullable: true);
          Field<Rock.GraphQL.Types.FinancialGateway>("FinancialGateway", resolve: x => x.Source.FinancialGateway);
          Field("FinancialGatewayId", x => x.FinancialGatewayId, nullable: true);
          Field<Rock.GraphQL.Types.FinancialPaymentDetail>("FinancialPaymentDetail", resolve: x => x.Source.FinancialPaymentDetail);
          Field("FinancialPaymentDetailId", x => x.FinancialPaymentDetailId, nullable: true);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("GatewayScheduleId", x => x.GatewayScheduleId, nullable: false);
          Field("IsActive", x => x.IsActive, nullable: false);
          Field("LastRemindedDate", x => x.LastRemindedDate, nullable: true);
          Field("LastStatusUpdateDateTime", x => x.LastStatusUpdateDateTime, nullable: true);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field("NextPaymentDate", x => x.NextPaymentDate, nullable: true);
          Field("NumberOfPayments", x => x.NumberOfPayments, nullable: true);
          Field<Rock.GraphQL.Types.DefinedValue>("SourceTypeValue", resolve: x => x.Source.SourceTypeValue);
          Field("SourceTypeValueId", x => x.SourceTypeValueId, nullable: true);
          Field("StartDate", x => x.StartDate, nullable: false);
          Field("TransactionCode", x => x.TransactionCode, nullable: false);
          Field<Rock.GraphQL.Types.DefinedValue>("TransactionFrequencyValue", resolve: x => x.Source.TransactionFrequencyValue);
          Field("TransactionFrequencyValueId", x => x.TransactionFrequencyValueId, nullable: false);
          Field<Rock.GraphQL.Types.DefinedValue>("TransactionTypeValue", resolve: x => x.Source.TransactionTypeValue);
          Field("TransactionTypeValueId", x => x.TransactionTypeValueId, nullable: true);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.FinancialScheduledTransaction GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.FinancialScheduledTransactionService(context.db);
           return service.Get(id);
       }
   }
}
