//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// GroupMember GraphQL Type
    /// </summary>
    public partial class GroupMember : ModelGraphType<Rock.Model.GroupMember>
    {
       public GroupMember(): base("GroupMember")
       {
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("DateTimeAdded", x => x.DateTimeAdded, nullable: true);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field<Rock.GraphQL.Types.Group>("Group", resolve: x => x.Source.Group);
          Field("GroupId", x => x.GroupId, nullable: false);
          Field<ListGraphType<Rock.GraphQL.Types.GroupMemberRequirement>>("GroupMemberRequirements", resolve: x => x.Source.GroupMemberRequirements);
          Field("GroupMemberStatus", x => x.GroupMemberStatus.ConvertToInt(), nullable: false);
          Field<Rock.GraphQL.Types.GroupTypeRole>("GroupRole", resolve: x => x.Source.GroupRole);
          Field("GroupRoleId", x => x.GroupRoleId, nullable: false);
          Field("GuestCount", x => x.GuestCount, nullable: true);
          Field("IsNotified", x => x.IsNotified, nullable: false);
          Field("IsSystem", x => x.IsSystem, nullable: false);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field("Note", x => x.Note, nullable: false);
          Field<Rock.GraphQL.Types.Person>("Person", resolve: x => x.Source.Person);
          Field("PersonId", x => x.PersonId, nullable: false);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.GroupMember GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.GroupMemberService(context.db);
           return service.Get(id);
       }
   }
}
