//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// GroupMemberWorkflowTrigger GraphQL Type
    /// </summary>
    public partial class GroupMemberWorkflowTrigger : ModelGraphType<Rock.Model.GroupMemberWorkflowTrigger>
    {
       public GroupMemberWorkflowTrigger(): base("GroupMemberWorkflowTrigger")
       {
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("GroupId", x => x.GroupId, nullable: true);
          Field("GroupTypeId", x => x.GroupTypeId, nullable: true);
          Field("IsActive", x => x.IsActive, nullable: false);
          Field("Name", x => x.Name, nullable: false);
          Field("Order", x => x.Order, nullable: false);
          Field("TriggerType", x => x.TriggerType.ConvertToInt(), nullable: false);
          Field("TypeQualifier", x => x.TypeQualifier, nullable: false);
          Field("WorkflowName", x => x.WorkflowName, nullable: false);
          Field<Rock.GraphQL.Types.WorkflowType>("WorkflowType", resolve: x => x.Source.WorkflowType);
          Field("WorkflowTypeId", x => x.WorkflowTypeId, nullable: false);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.GroupMemberWorkflowTrigger GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.GroupMemberWorkflowTriggerService(context.db);
           return service.Get(id);
       }
   }
}
