//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// PersonViewed GraphQL Type
    /// </summary>
    public partial class PersonViewed : ModelGraphType<Rock.Model.PersonViewed>
    {
       public PersonViewed(): base("PersonViewed")
       {
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IpAddress", x => x.IpAddress, nullable: false);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("Source", x => x.Source, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("TargetPersonAlias", resolve: x => x.Source.TargetPersonAlias);
          Field("TargetPersonAliasId", x => x.TargetPersonAliasId, nullable: true);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("ViewDateTime", x => x.ViewDateTime, nullable: true);
          Field<Rock.GraphQL.Types.PersonAlias>("ViewerPersonAlias", resolve: x => x.Source.ViewerPersonAlias);
          Field("ViewerPersonAliasId", x => x.ViewerPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.PersonViewed GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.PersonViewedService(context.db);
           return service.Get(id);
       }
   }
}
