//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// PhoneNumber GraphQL Type
    /// </summary>
    public partial class PhoneNumber : ModelGraphType<Rock.Model.PhoneNumber>
    {
       public PhoneNumber(): base("PhoneNumber")
       {
          Field("CountryCode", x => x.CountryCode, nullable: false);
          Field("Description", x => x.Description, nullable: false);
          Field("Extension", x => x.Extension, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IsMessagingEnabled", x => x.IsMessagingEnabled, nullable: false);
          Field("IsSystem", x => x.IsSystem, nullable: false);
          Field("IsUnlisted", x => x.IsUnlisted, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field("Number", x => x.Number, nullable: false);
          Field("NumberFormatted", x => x.NumberFormatted, nullable: false);
          Field<Rock.GraphQL.Types.DefinedValue>("NumberTypeValue", resolve: x => x.Source.NumberTypeValue);
          Field("NumberTypeValueId", x => x.NumberTypeValueId, nullable: true);
          Field("PersonId", x => x.PersonId, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.PhoneNumber GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.PhoneNumberService(context.db);
           return service.Get(id);
       }
   }
}
