//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// RegistrationTemplateFormField GraphQL Type
    /// </summary>
    public partial class RegistrationTemplateFormField : ModelGraphType<Rock.Model.RegistrationTemplateFormField>
    {
       public RegistrationTemplateFormField(): base("RegistrationTemplateFormField")
       {
          Field<Rock.GraphQL.Types.Attribute>("Attribute", resolve: x => x.Source.Attribute);
          Field("AttributeId", x => x.AttributeId, nullable: true);
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field("FieldSource", x => x.FieldSource.ConvertToInt(), nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IsGridField", x => x.IsGridField, nullable: false);
          Field("IsInternal", x => x.IsInternal, nullable: false);
          Field("IsRequired", x => x.IsRequired, nullable: false);
          Field("IsSharedValue", x => x.IsSharedValue, nullable: false);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field("Order", x => x.Order, nullable: false);
          Field("PersonFieldType", x => x.PersonFieldType.ConvertToInt(), nullable: false);
          Field("PostText", x => x.PostText, nullable: false);
          Field("PreText", x => x.PreText, nullable: false);
          Field<Rock.GraphQL.Types.RegistrationTemplateForm>("RegistrationTemplateForm", resolve: x => x.Source.RegistrationTemplateForm);
          Field("RegistrationTemplateFormId", x => x.RegistrationTemplateFormId, nullable: false);
          Field("ShowCurrentValue", x => x.ShowCurrentValue, nullable: false);
          Field("ShowOnWaitlist", x => x.ShowOnWaitlist, nullable: false);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.RegistrationTemplateFormField GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.RegistrationTemplateFormFieldService(context.db);
           return service.Get(id);
       }
   }
}
