//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// RegistrationRegistrant GraphQL Type
    /// </summary>
    public partial class RegistrationRegistrant : ModelGraphType<Rock.Model.RegistrationRegistrant>
    {
       public RegistrationRegistrant(): base("RegistrationRegistrant")
       {
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field("Cost", x => x.Cost, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("DiscountApplies", x => x.DiscountApplies, nullable: false);
          Field("Email", x => x.Email, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field<ListGraphType<Rock.GraphQL.Types.RegistrationRegistrantFee>>("Fees", resolve: x => x.Source.Fees);
          Field("FirstName", x => x.FirstName, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field<Rock.GraphQL.Types.GroupMember>("GroupMember", resolve: x => x.Source.GroupMember);
          Field("GroupMemberId", x => x.GroupMemberId, nullable: true);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("LastName", x => x.LastName, nullable: false);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field("NickName", x => x.NickName, nullable: false);
          Field("OnWaitList", x => x.OnWaitList, nullable: false);
          Field<Rock.GraphQL.Types.Person>("Person", resolve: x => x.Source.Person);
          Field<Rock.GraphQL.Types.PersonAlias>("PersonAlias", resolve: x => x.Source.PersonAlias);
          Field("PersonAliasId", x => x.PersonAliasId, nullable: true);
          Field("PersonId", x => x.PersonId, nullable: true);
          Field<Rock.GraphQL.Types.Registration>("Registration", resolve: x => x.Source.Registration);
          Field("RegistrationId", x => x.RegistrationId, nullable: false);
          Field("TotalCost", x => x.TotalCost, nullable: false);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.RegistrationRegistrant GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.RegistrationRegistrantService(context.db);
           return service.Get(id);
       }
   }
}
