//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// UserLogin GraphQL Type
    /// </summary>
    public partial class UserLogin : ModelGraphType<Rock.Model.UserLogin>
    {
       public UserLogin(): base("UserLogin")
       {
          Field("ApiKey", x => x.ApiKey, nullable: false);
          Field<Rock.GraphQL.Types.EntityType>("EntityType", resolve: x => x.Source.EntityType);
          Field("EntityTypeId", x => x.EntityTypeId, nullable: true);
          Field("FailedPasswordAttemptCount", x => x.FailedPasswordAttemptCount, nullable: true);
          Field("FailedPasswordAttemptWindowStartDateTime", x => x.FailedPasswordAttemptWindowStartDateTime, nullable: true);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IsConfirmed", x => x.IsConfirmed, nullable: true);
          Field("IsLockedOut", x => x.IsLockedOut, nullable: true);
          Field("IsOnLine", x => x.IsOnLine, nullable: true);
          Field("IsPasswordChangeRequired", x => x.IsPasswordChangeRequired, nullable: true);
          Field("LastActivityDateTime", x => x.LastActivityDateTime, nullable: true);
          Field("LastLockedOutDateTime", x => x.LastLockedOutDateTime, nullable: true);
          Field("LastLoginDateTime", x => x.LastLoginDateTime, nullable: true);
          Field("LastPasswordChangedDateTime", x => x.LastPasswordChangedDateTime, nullable: true);
          Field("LastPasswordExpirationWarningDateTime", x => x.LastPasswordExpirationWarningDateTime, nullable: true);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field("PersonId", x => x.PersonId, nullable: true);
          Field("UserName", x => x.UserName, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.UserLogin GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.UserLoginService(context.db);
           return service.Get(id);
       }
   }
}
