//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// WorkflowType GraphQL Type
    /// </summary>
    public partial class WorkflowType : ModelGraphType<Rock.Model.WorkflowType>
    {
       public WorkflowType(): base("WorkflowType")
       {
          Field<Rock.GraphQL.Types.Category>("Category", resolve: x => x.Source.Category);
          Field("CategoryId", x => x.CategoryId, nullable: true);
          Field("CompletedWorkflowRetentionPeriod", x => x.CompletedWorkflowRetentionPeriod, nullable: true);
          Field("Description", x => x.Description, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IconCssClass", x => x.IconCssClass, nullable: false);
          Field("IsActive", x => x.IsActive, nullable: true);
          Field("IsPersisted", x => x.IsPersisted, nullable: false);
          Field("IsSystem", x => x.IsSystem, nullable: false);
          Field("LoggingLevel", x => x.LoggingLevel.ConvertToInt(), nullable: false);
          Field("LogRetentionPeriod", x => x.LogRetentionPeriod, nullable: true);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field("Name", x => x.Name, nullable: false);
          Field("NoActionMessage", x => x.NoActionMessage, nullable: false);
          Field("Order", x => x.Order, nullable: false);
          Field("ProcessingIntervalSeconds", x => x.ProcessingIntervalSeconds, nullable: true);
          Field("SummaryViewText", x => x.SummaryViewText, nullable: false);
          Field("WorkflowIdPrefix", x => x.WorkflowIdPrefix, nullable: false);
          Field("WorkTerm", x => x.WorkTerm, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.WorkflowType GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.WorkflowTypeService(context.db);
           return service.Get(id);
       }
   }
}
