//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using GraphQL;
using GraphQL.Types;
using Rock.Model;

namespace Rock.GraphQL.Types
{
    /// <summary>
    /// WorkflowActivity GraphQL Type
    /// </summary>
    public partial class WorkflowActivity : ModelGraphType<Rock.Model.WorkflowActivity>
    {
       public WorkflowActivity(): base("WorkflowActivity")
       {
          Field<ListGraphType<Rock.GraphQL.Types.WorkflowAction>>("Actions", resolve: x => x.Source.Actions);
          Field<Rock.GraphQL.Types.WorkflowActivity>("ActivatedByActivity", resolve: x => x.Source.ActivatedByActivity);
          Field("ActivatedByActivityId", x => x.ActivatedByActivityId, nullable: true);
          Field("ActivatedDateTime", x => x.ActivatedDateTime, nullable: true);
          Field<Rock.GraphQL.Types.WorkflowActivityType>("ActivityType", resolve: x => x.Source.ActivityType);
          Field("ActivityTypeId", x => x.ActivityTypeId, nullable: false);
          Field<Rock.GraphQL.Types.Group>("AssignedGroup", resolve: x => x.Source.AssignedGroup);
          Field("AssignedGroupId", x => x.AssignedGroupId, nullable: true);
          Field<Rock.GraphQL.Types.PersonAlias>("AssignedPersonAlias", resolve: x => x.Source.AssignedPersonAlias);
          Field("AssignedPersonAliasId", x => x.AssignedPersonAliasId, nullable: true);
          Field("CompletedDateTime", x => x.CompletedDateTime, nullable: true);
          Field("ContextKey", x => x.ContextKey, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("CreatedByPersonAlias", resolve: x => x.Source.CreatedByPersonAlias);
          Field("CreatedByPersonId", x => x.CreatedByPersonId, nullable: true);
          Field("CreatedByPersonName", x => x.CreatedByPersonName, nullable: false);
          Field("EncryptedKey", x => x.EncryptedKey, nullable: false);
          Field("ForeignGuid", x => x.ForeignGuid.ToStringSafe(), nullable: true);
          Field("ForeignKey", x => x.ForeignKey, nullable: false);
          Field("IsActive", x => x.IsActive, nullable: false);
          Field("IsValid", x => x.IsValid, nullable: false);
          Field("LastProcessedDateTime", x => x.LastProcessedDateTime, nullable: true);
          Field("ModifiedAuditValuesAlreadyUpdated", x => x.ModifiedAuditValuesAlreadyUpdated, nullable: false);
          Field<Rock.GraphQL.Types.PersonAlias>("ModifiedByPersonAlias", resolve: x => x.Source.ModifiedByPersonAlias);
          Field("ModifiedByPersonId", x => x.ModifiedByPersonId, nullable: true);
          Field("ModifiedByPersonName", x => x.ModifiedByPersonName, nullable: false);
          Field("TypeId", x => x.TypeId, nullable: false);
          Field("TypeName", x => x.TypeName, nullable: false);
          Field("UrlEncodedKey", x => x.UrlEncodedKey, nullable: false);
          Field<Rock.GraphQL.Types.Workflow>("Workflow", resolve: x => x.Source.Workflow);
          Field("WorkflowId", x => x.WorkflowId, nullable: false);
          Field("CreatedDateTime", x => x.CreatedDateTime, nullable: true);
          Field("ModifiedDateTime", x => x.ModifiedDateTime, nullable: true);
          Field("CreatedByPersonAliasId", x => x.CreatedByPersonAliasId, nullable: true);
          Field("ModifiedByPersonAliasId", x => x.ModifiedByPersonAliasId, nullable: true);
          Field("Guid", x => x.Guid.ToStringSafe(), nullable: false);
          Field("ForeignId", x => x.ForeignId, nullable: true);
       }
       public override Rock.Model.WorkflowActivity GetById(int id, GraphQLContext context)
       {
           var service = new Rock.Model.WorkflowActivityService(context.db);
           return service.Get(id);
       }
   }
}
